### ISSUE TITLE
Configure RESTful interface for db001.gda-score.org

### ISSUE THREAD

**Issue by yoid2000** [gda-score/anon-methods#8]
Some of the anonymization systems (i.e. #6) we need to talk to may not have a postgres ODBC interface. For these, I would like to use a RESTful interface and whatever custom code we need to interact with the anonymization system.

I don't have an opinion on the best web server to use for this. Apache may be fine, nginx may be fine, something else may be fine. Note that we don't need particularly high performance here...I think the performance bottleneck will most likely be at the anonymization system itself. We also don't have strong security requirements.

For this task, please make operational a REST interface and some simple stub code on the server side written in python. We should be able to pass JSON to the python stub, and have the stub pass JSON back.

I'll separately make a ticket with our IT folks to install whatever software is needed on the server and to give you a login account.

**Comment by yoid2000** [comment]
> I saw all the requirements and the tickets. So from what I 
understood, I will create a REST API using Python which 
can handle requests in JSON format and return the results 
of the requests in JSON. This API will connect to db001 
and the API should have the capability of dynamically 
handling requests from the user as to which database to 
retrieve results from. I did some research and found that 
Flask framework will be good for building this REST 
interface.
After the API is finished you want it to run on the Apache 
server.

> Is my understanding of the requirements correct? If this 
is the task, then I'll proceed with building the 
interface.

I was thinking that Apache itself would implement the REST API, but I'm a bit unsure about that. Let me ask one of my colleagues and get back.

**Comment by yoid2000** [comment]
By the way, please ask these kinds of questions on github itself. Then I have a record and know where to find it.

**Comment by yoid2000** [comment]
@rbh-93 

Ok, I see there are a lot of options for what tech base to use for this, and I don't have a strong opinion. So let me try to write the requirements in generic terms.

On the client side, I would like to be able to write a json string to a URL, and read the returned json string. On the server side, I would like to be able to write glue code that either listens for incoming json strings, or is invoked by something else and handed a json string, and then responds with a json string.

I don't think we have particularly strict performance requirements, though the json string from server to client could be fairly long (some mega-bytes). This should certainly all work with python. Being able to work with other languages is a plus.

Ok, how best to do that then I'll leave to you  ;)

**Comment by yoid2000** [comment]
What is important though is to keep it simple, use mature libraries, and minimize dependencies...

**Comment by rbh-93** [comment]
Ok. Thank you for the clarification. I will start working on it.

**Comment by rbh-93** [comment]
For the REST interface, I have created the GET method. Do you need PUT, POST and DELETE methods as well? Is the front-end meant for only retrieving data from db001 or should it also handle manipulation of data like insertion, deletion of data as well?

**Comment by yoid2000** [comment]
No, it is only what I said in the above comment:

> On the client side, I would like to be able to write a json string to a URL, and read the returned json string. On the server side, I would like to be able to write glue code that either listens for incoming json strings, or is invoked by something else and handed a json string, and then responds with a json string.

**Comment by rbh-93** [comment]
The back-end GET method is done. At the moment I am running the script on the banking database on my localhost. For running it on the server, just the database connection parameters (server name, port, credentials) need to be changed depending on which database you want to run it on. Is there any particular database or would it be taken as input from the user?
I will start working on the front-end part. How do you want the front-end interface to be designed and what will be the input/query parameters (fields to run the get method on)? For example, at the moment invoking the GET methods on the banking database runs a ''SELECT * from accounts'' and "SELECT * FROM accounts where account_id = xxx" queries on the accounts table.

**Comment by yoid2000** [comment]
There may be some confusion as to what should be done here. For instance, this task has nothing to do with SQL or accessing the database ("db001" is just the name of the machine. I didn't mean to imply that you should actually access the database).

Let's make it simpler. Please just write a client that sends JSON to the server using a GET. Write a server that listens for the GET, and then just places the JSON in a file, and then return the JSON back to the client. This client and server code can then work as sample code for future tasks.

Does this make sense???

**Comment by rbh-93** [comment]
Okay. I see. Then I just need to modify the back-end code a bit. Thank you for the clarification.

**Comment by rbh-93** [comment]
Hi,
The task is done. This is what I have implemented:
The client can paste JSON to url and send it to the server via Get request. The server listens for incoming get requests, receives this url from the client and extracts the parameters from the url. Then it writes them to a file in JSON. Finally, the server returns the extracted JSON to the client which displays them in JSON format. 
The files are created in the project directory with a timestamp in the filename. 
Are there any changes/modifications in the above workflow? Would you like to review the code?

**Comment by yoid2000** [comment]
Hi Rohan. Yes I would like to see the code. Could you punch it to the test
directory?

PF

**Comment by yoid2000** [comment]
I meant push.

**Comment by rbh-93** [comment]
Should I create a test directory under anon-methods or upload it to my git?

**Comment by rbh-93** [comment]
I mean fork anon-methods to my git and push it there? You can review the code there.

**Comment by rbh-93** [comment]
https://github.com/rbh-93/anon-methods

**Comment by yoid2000** [comment]
Wow that looks super simple! And I gather that the server runs in a continuous loop? (I was looking for the while loop, but I’m guessing that app.run() holds the loop?)

**Comment by yoid2000** [comment]
Anyway, please push these two files to a folder called examples. Call them simpleClient and simpleServer. Then close this issue.

**Comment by rbh-93** [comment]
> Anyway, please push these two files to a folder called examples. Call them simpleClient and simpleServer. Then close this issue.

Done. Closing the issue.
